########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # mongodb
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog
  # 开启aop
  aop:
    auto: true
  # 应用环境配置
  profiles:
    active: development
  # kafka配置
  kafka:
    producer:
      acks: 1
      retries: 0
      batch-size: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: application
      auto-offset-reset: earliest
      enable-auto-commit: false
      fetch-max-wait: 5000
      max-poll-records: 100
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


######### 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles

---

# 生产环境配置

spring:
  profiles: production
  redis:
    cluster:
      nodes: 127.0.0.1:7001


---

# 开发环境配置

spring:
  profiles: development
  redis:
    cluster:
      nodes: 45.77.6.109:7001
  kafka:
    bootstrap-servers: 45.77.6.109:9092
    template:
      default-topic: test1
    system-msg:
      topic: test1
      timeout: 3000
