########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # mongodb
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog
  # 开启aop
  aop:
    auto: true
  # 应用环境配置
  profiles:
    active: development


######### 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles

---

# 生产环境配置

spring:
  profiles: production
  redis:
    cluster:
      nodes: 127.0.0.1:7001


---

# 开发环境配置

spring:
  profiles: development
  redis:
    cluster:
      nodes: 45.77.6.109:7001
  kafka:
    bootstrap-servers: 45.77.6.109:9092
    consumer:
      group-id: testconsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    template:
      default-topic: testv2
    producer:
      bootstrap-servers: 45.77.6.109:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    system-msg:
      topic: testsys
      timeout: 3000
