########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # 开启aop
  aop:
    auto: true
  # 应用环境配置
  profiles:
    active: development
  # session
  #session:
  #  store-type: redis

# mongodb
mongodb:
  host: 127.0.0.1
  port: 27017
  database: don9blog
  username: liuxindong
  password: 123456

# 文件保存路径
fileSavePath:
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles

---

############### 生产环境配置

spring:
  profiles: production
  redis:
    host: 127.0.0.1
    port: 6379
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    default-queue: system.queue
    default-topic: system
    system-msg-topic: system
    system-listener-clientId: Application

# 文件保存路径
fileSavePath:
  serverUrl: http://47.94.206.26:8999
  serverRoot: /var/www/html

---

############### 开发环境配置

spring:
  profiles: development
  redis:
    host: 47.94.206.26
    port: 6379
  activemq:
    broker-url: tcp://47.94.206.26:61616
    user: admin
    password: admin
    default-queue: test.queue
    default-topic: test
    system-msg-topic: test
    system-listener-clientId: devApplication

# 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs

