########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # mongodb
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog
  # 开启aop
  aop:
    auto: true


######### 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles



