########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # 开启aop
  aop:
    auto: true
  # 应用环境配置
  profiles:
    active: development
  # kafka配置
  kafka:
    producer:
      acks: 1
      retries: 0
      batch-size: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: application
      auto-offset-reset: earliest
      enable-auto-commit: true
      fetch-max-wait: 3000
      max-poll-records: 1000
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-min-size: 0




---

############### 生产环境配置

spring:
  profiles: production
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog

---

############### 开发环境配置

spring:
  profiles: development
  redis:
    host: 47.94.206.26
    port: 6379
  kafka:
    bootstrap-servers: 47.94.206.26:9092
    template:
      default-topic: test
    system-msg:
      topic: test
      timeout: 2000
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog

# 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles
