########### spring
spring:
  #-----------------------------------------> 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  #-----------------------------------------> 多文件上传
  http:
    multipart:
      enabled: true
  #-----------------------------------------> 开启aop
  aop:
    auto: true
  #-----------------------------------------> activeMq配置
  activemq:
      broker-url: tcp://45.77.6.109:61616
      user: admin
      password: admin
  #-----------------------------------------> session共享
  #session:
  #  store-type: redis
  #-----------------------------------------> 应用环境配置
  profiles:
    active: development


#-------------------------------------------> mongodb数据库配置
mongodb:
  host: 127.0.0.1
  port: 27017
  database: don9blog
  username: liuxindong
  password: 123456

#-------------------------------------------> 文件(上传文件以及上传图片)保存路径
fileSavePath:
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles

---

############### 生产环境配置

spring:
  profiles: production
  redis:
    host: 127.0.0.1
    port: 6379
  activemq:
    queue-default: queue-default
    topic-default: topic-default
    topic-msg-system: topic-msg-system
    topic-mail-register: topic-mail-register
    topic-mail-subscribe: topic-mail-subscribe
    system-listener-clientId: Pro_BlogApplication

# 文件保存路径
fileSavePath:
  serverUrl: http://47.94.206.26:8999
  serverRoot: /var/www/html

---

############### 开发环境配置

spring:
  profiles: development
  redis:
    host: 47.94.206.26
    port: 6379
  activemq:
    queue-default: queue-default
    topic-default: topic-default
    topic-msg-system: systemtest
    topic-mail-register: mailtest
    topic-mail-subscribe: subscribetest
    system-listener-clientId: Dev_BlogApplication

# 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs

# 关闭spring boot状态管理权限
management:
  security:
    enabled: false



