
spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://45.76.212.6:3306/don9blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 921220
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true

##############  控制spring security开关  ##############
management:
  security:
    enabled: false

##############  mybatis  ##############
mybatis:
  type-aliases-package: cn.don9cn.blog.model
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    default-statement-timeout: 60000
    lazy-loading-enabled: false

##############  分页插件pageHelper  ##############
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: false
  page-size-zero: true
  reasonable: false

##############  文件保存路径  ##############
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles


