########### spring
spring:
  # 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main
  # 多文件上传
  http:
    multipart:
      enabled: true
  # 开启aop
  aop:
    auto: true
  # 应用环境配置
  profiles:
    active: development




---

############### 生产环境配置

spring:
  profiles: production
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@127.0.0.1:27017/don9blog

---

############### 开发环境配置

spring:
  profiles: development
  redis:
    host: 47.94.206.26
    port: 6379
  data:
    mongodb:
      uri: mongodb://liuxindong:123456@47.94.206.26:27017/don9blog
      options:
        connections-per-host: 8
        threads-allowed-to-block-for-connection-multiplier: 4
        connect-timeout: 1000
        max-wait-time: 1500
        auto-connect-retry: true
        socket-keep-alive: true
        socket-timeout: 1500
  activemq:
    broker-url: tcp://45.77.6.109:61616
    user: admin
    password: admin
    default-queue: test.queue
    default-topic: test.topic
    system-msg-topic: test
    system-listener-clientId: Application
# 文件保存路径
fileSavePath:
  serverUrl: http://localhost:9999
  serverRoot: E:/Apache24/htdocs
  images: /don9cn/images
  uploadFiles: /don9cn/uploadFiles
